import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      <img src='logo.jpg'></img>
        
        <h1 className={styles.title}>
          SUPREME <a href="./users"> STORE </a>
        </h1>

        <p>SUPREME STORE é expert nos cuidados com a moda, realizando constantes investimentos em novos vestuários da moda</p>

       

        <div className={styles.grid}>
          <a href="./contato" className={styles.card}>
            <h2> Contato &rarr;</h2>
            <p> Acesse aqui. </p>
          </a>

          <a href="./produtos" className={styles.card}>
            <h2> NOSSOS PRODUTOS  &rarr;</h2>
            <p> Acesse aqui.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
